import 'package:core_bloc/core_bloc.dart';
import 'package:firebase_auth/firebase_auth.dart';
// import 'package:firebase_app_check/firebase_app_check.dart';  // Temporarily disabled
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:operon_driver_android/config/firebase_options.dart';
import 'package:operon_driver_android/core/models/location_point.dart';
import 'package:operon_driver_android/presentation/app.dart';

@pragma('vm:entry-point')
void onStart(ServiceInstance service) {
  if (service is AndroidServiceInstance) {
    service.on('setAsForeground').listen((_) {
      service.setAsForegroundService();
    });
    service.on('setAsBackground').listen((_) {
      service.setAsBackgroundService();
    });
  }

  service.on('stopService').listen((_) {
    service.stopSelf();
  });
}

Future<void> initializeService() async {
  final service = FlutterBackgroundService();

  await service.configure(
    androidConfiguration: AndroidConfiguration(
      onStart: onStart,
      autoStart: false,
      isForegroundMode: true,
      initialNotificationTitle: 'Operon Driver',
      initialNotificationContent: 'Trip tracking active',
      foregroundServiceNotificationId: 777,
    ),
    iosConfiguration: IosConfiguration(
      autoStart: false,
      onForeground: onStart,
    ),
  );
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive for offline location storage
  try {
    await Hive.initFlutter();
    // Register LocationPoint adapter (generated by build_runner)
    // Note: Run 'flutter pub run build_runner build' to generate the adapter
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(LocationPointAdapter());
    }
    debugPrint('[main] Hive initialized successfully');
  } catch (e) {
    debugPrint('[main] Hive initialization failed: $e');
    // Continue even if Hive fails - location service will handle gracefully
  }

  try {
    // Check if Firebase is already initialized (prevents duplicate app error on hot restart)
    try {
      Firebase.app(); // Try to get default app - will throw if not initialized
      debugPrint('[main] Firebase already initialized, skipping initialization...');
    } catch (_) {
      // Firebase not initialized, initialize it now
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
      debugPrint('[main] Firebase initialized successfully');
    }

    if (kDebugMode) {
      await FirebaseAuth.instance.setSettings(
        appVerificationDisabledForTesting: true,
      );
      debugPrint('[main] App verification disabled for testing (DEBUG ONLY)');
    }

    // // Initialize Firebase App Check
    // try {
    //   if (kDebugMode) {
    //     await FirebaseAppCheck.instance.activate(
    //       androidProvider: AndroidProvider.debug,
    //     );
    //     debugPrint('[main] App Check activated with debug provider');
    //   } else {
    //     await FirebaseAppCheck.instance.activate(
    //       androidProvider: AndroidProvider.playIntegrity,
    //     );
    //     debugPrint('[main] App Check activated with Play Integrity provider');
    //   }
    // } catch (e) {
    //   debugPrint('[main] App Check initialization failed: $e');
    //   // Continue even if App Check fails - it's not critical for basic functionality
    // }
  } catch (e, stackTrace) {
    // Only log if it's not a duplicate app error (which we handle above)
    if (!e.toString().contains('duplicate-app')) {
      debugPrint('[main] Firebase initialization failed: $e');
      debugPrint('[main] Stack trace: $stackTrace');
    }
  }

  await initializeService();

  Bloc.observer = const AppBlocObserver();
  runApp(const OperonDriverApp());
}
