import 'package:cloud_firestore/cloud_firestore.dart';

class ClientAddress {
  final String? street;
  final String? city;
  final String? state;
  final String? zipCode;
  final String? country;

  ClientAddress({
    this.street,
    this.city,
    this.state,
    this.zipCode,
    this.country,
  });

  Map<String, dynamic> toMap() {
    return {
      if (street != null) 'street': street,
      if (city != null) 'city': city,
      if (state != null) 'state': state,
      if (zipCode != null) 'zipCode': zipCode,
      if (country != null) 'country': country,
    };
  }

  factory ClientAddress.fromMap(Map<String, dynamic>? data) {
    if (data == null) return ClientAddress();
    return ClientAddress(
      street: data['street'] as String?,
      city: data['city'] as String?,
      state: data['state'] as String?,
      zipCode: data['zipCode'] as String?,
      country: data['country'] as String?,
    );
  }
}

class Client {
  final String? id;
  final String clientId;
  final String organizationId;
  final String name;
  final String phoneNumber;
  final String? email;
  final ClientAddress? address;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String? createdBy;
  final String? updatedBy;
  final String status;
  final String? notes;
  final List<String>? tags;
  final List<String>? phoneList;

  Client({
    this.id,
    this.clientId = '', // Optional - will be generated by backend if not provided
    required this.organizationId,
    required this.name,
    required this.phoneNumber,
    this.email,
    this.address,
    required this.createdAt,
    required this.updatedAt,
    this.createdBy,
    this.updatedBy,
    this.status = ClientStatus.active,
    this.notes,
    this.tags,
    this.phoneList,
  });

  factory Client.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    return Client(
      id: doc.id,
      clientId: data['clientId'] as String? ?? doc.id,
      organizationId: data['organizationId'] as String? ?? '',
      name: data['name'] as String? ?? '',
      phoneNumber: data['phoneNumber'] as String? ?? '',
      email: data['email'] as String?,
      address: data['address'] != null
          ? ClientAddress.fromMap(data['address'] as Map<String, dynamic>?)
          : null,
      createdAt: data['createdAt'] != null
          ? (data['createdAt'] as Timestamp).toDate()
          : DateTime.now(),
      updatedAt: data['updatedAt'] != null
          ? (data['updatedAt'] as Timestamp).toDate()
          : DateTime.now(),
      createdBy: data['createdBy'] as String?,
      updatedBy: data['updatedBy'] as String?,
      status: data['status'] as String? ?? ClientStatus.active,
      notes: data['notes'] as String?,
      tags: data['tags'] != null
          ? List<String>.from(data['tags'] as List)
          : null,
      phoneList: data['phoneList'] != null
          ? List<String>.from(data['phoneList'] as List)
          : null,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'clientId': clientId,
      'organizationId': organizationId,
      'name': name,
      'phoneNumber': phoneNumber,
      if (email != null) 'email': email,
      if (address != null) 'address': address!.toMap(),
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': Timestamp.fromDate(updatedAt),
      if (createdBy != null) 'createdBy': createdBy,
      if (updatedBy != null) 'updatedBy': updatedBy,
      'status': status,
      if (notes != null) 'notes': notes,
      if (tags != null) 'tags': tags,
      if (phoneList != null) 'phoneList': phoneList,
    };
  }

  Client copyWith({
    String? clientId,
    String? organizationId,
    String? name,
    String? phoneNumber,
    String? email,
    ClientAddress? address,
    DateTime? updatedAt,
    String? updatedBy,
    String? status,
    String? notes,
    List<String>? tags,
    List<String>? phoneList,
  }) {
    return Client(
      id: id,
      clientId: clientId ?? this.clientId,
      organizationId: organizationId ?? this.organizationId,
      name: name ?? this.name,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      email: email ?? this.email,
      address: address ?? this.address,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      createdBy: createdBy,
      updatedBy: updatedBy ?? this.updatedBy,
      status: status ?? this.status,
      notes: notes ?? this.notes,
      tags: tags ?? this.tags,
      phoneList: phoneList ?? this.phoneList,
    );
  }

  bool get isActive => status == ClientStatus.active;
}

class ClientStatus {
  static const String active = 'active';
  static const String inactive = 'inactive';
  static const String archived = 'archived';

  static const List<String> all = [
    active,
    inactive,
    archived,
  ];
}

