"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TRANSACTIONS_SOURCE_KEY = exports.SOURCE_KEY = exports.WHATSAPP_SETTINGS_COLLECTION = exports.ORGANIZATIONS_COLLECTION = exports.PENDING_ORDERS_COLLECTION = exports.CLIENT_LEDGERS_COLLECTION = exports.TRANSACTIONS_COLLECTION = exports.CLIENTS_COLLECTION = exports.ANALYTICS_COLLECTION = void 0;
exports.ANALYTICS_COLLECTION = 'ANALYTICS';
exports.CLIENTS_COLLECTION = 'CLIENTS';
exports.TRANSACTIONS_COLLECTION = 'TRANSACTIONS';
exports.CLIENT_LEDGERS_COLLECTION = 'CLIENT_LEDGERS';
exports.PENDING_ORDERS_COLLECTION = 'PENDING_ORDERS';
exports.ORGANIZATIONS_COLLECTION = 'ORGANIZATIONS';
exports.WHATSAPP_SETTINGS_COLLECTION = 'WHATSAPP_SETTINGS';
exports.SOURCE_KEY = 'clients';
exports.TRANSACTIONS_SOURCE_KEY = 'transactions';
//# sourceMappingURL=constants.js.map