export const ANALYTICS_COLLECTION = 'ANALYTICS';
export const CLIENTS_COLLECTION = 'CLIENTS';
export const TRANSACTIONS_COLLECTION = 'TRANSACTIONS';
export const CLIENT_LEDGERS_COLLECTION = 'CLIENT_LEDGERS';
export const PENDING_ORDERS_COLLECTION = 'PENDING_ORDERS';
export const ORGANIZATIONS_COLLECTION = 'ORGANIZATIONS';
export const WHATSAPP_SETTINGS_COLLECTION = 'WHATSAPP_SETTINGS';
export const SOURCE_KEY = 'clients';
export const TRANSACTIONS_SOURCE_KEY = 'transactions';

