export const ANALYTICS_COLLECTION = 'ANALYTICS';
export const CLIENTS_COLLECTION = 'CLIENTS';
export const TRANSACTIONS_COLLECTION = 'TRANSACTIONS';
export const CLIENT_LEDGERS_COLLECTION = 'CLIENT_LEDGERS';
export const VENDORS_COLLECTION = 'VENDORS';
export const VENDOR_LEDGERS_COLLECTION = 'VENDOR_LEDGERS';
export const EMPLOYEES_COLLECTION = 'EMPLOYEES';
export const EMPLOYEE_LEDGERS_COLLECTION = 'EMPLOYEE_LEDGERS';
export const ORGANIZATION_LEDGERS_COLLECTION = 'ORGANIZATION_LEDGERS';
export const EXPENSE_SUB_CATEGORIES_COLLECTION = 'EXPENSE_SUB_CATEGORIES';
export const PENDING_ORDERS_COLLECTION = 'PENDING_ORDERS';
export const ORGANIZATIONS_COLLECTION = 'ORGANIZATIONS';
export const WHATSAPP_SETTINGS_COLLECTION = 'WHATSAPP_SETTINGS';
export const SOURCE_KEY = 'clients';
export const TRANSACTIONS_SOURCE_KEY = 'transactions';

